version: "3.0"
services:
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=dracula
    restart: always
    ports:
      - 8080:8080

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
      - MYSQL_USER=pontus
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_PASSWORD=1234567
      - MYSQL_DATABASE=djangoboard
    volumes:
      - ./appdata/mariadb:/config
    ports:
      - 3306:3306/tcp

  django:
    container_name: django
    build:
      context: ./DjangoBoard
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DjangoBoard:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=09300930930930j9j9j9j9
    depends_on:
      - mariadb